### ISSUE TITLE
API-Keys not used

### ISSUE THREAD

**Issue by jamfx** [jason5ng32/MyIP#287]
## Environment:

* Debian 12
* FF and Chromium
* Node Version: */*
* Vite Version:*/*
* Vue3 Version: */*
* Docker Version (if applicable):
* Deployment Method (Vercel/Docker/Node): Docker - latest
* Environment Variables (without sensitive info): 
* Any other relevant software versions:

## Description:
I tried to pull up the Docker with some of the API-Keys I could obtain for free. 
But the where not used!

Steps to Reproduce:
1. Set up IPChecking-Docker (latest) with docker-compose file behind traefik (Reverse Proxy)
2. Start Docker Container.
3. Try to check the location 
4. No location is shown and also in the side-bar all services are crossed out

![Image](https://github.com/user-attachments/assets/10abbf4e-2a7e-4f2d-88bb-016eb28d627a)

![Image](https://github.com/user-attachments/assets/c9abf86e-1245-4954-9cd3-fcfa2294ec4c)

## Expected Behavior:
I would love to see the location

## Actual Behavior:

No location shown. All services are crossed out.

## Terminal & Console Logs:
No Bugs in log. 🤷‍♂ 

Additional Context:

My .env-file

```
IPINFO_API_TOKEN="MYKEY"
IPAPIIS_API_KEY="MYKEY"
IP2LOCATION_API_KEY="MYKEY"

```
My docker-compose file
```

services:
  myip:
    image: jason5ng32/myip:latest
    container_name: myip
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myip.entrypoints=websecure"
      - "traefik.http.routers.myip.rule=Host(`SUB.MYDOMAIN.COM`)"
      - "traefik.http.routers.myip.tls=true"
      - "traefik.http.routers.myip.tls.certresolver=letsencrypt"
      - "traefik.http.routers.myip.service=myip"
      - "traefik.http.services.myip.loadbalancer.server.port=18966"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
    env_file:
      - .env 
networks:
  proxy:
    external: true
```

I would also like to know, how to obtain an API-Key for ipcheck.ing. Where do I get this API-Key? Even after registration, I could not find any. 
Ah, and the WEBRTC-Checks do all fail with. "NAT: Awaiting Test or Connection Error"

Thanks for your help in advance.
Niko
